name: AvalonyaAPI
version: '${project.version}'
main: eu.avalonya.api.AvalonyaAPI
api-version: '1.20'
commands:
  demo:
    description: Demo command
  setrank:
    description: Set rank command
    permission: avalonya.admin
permissions:
  avalonya.admin:
    description: toto
    default: false
  avalonya.*:
    description: all perm
    default: false
    children:
      avalonya.admin: true

