// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avalonya.proto

package eu.avalonya.api.protobuf;

public final class AvalonyaProtobuffers {
  private AvalonyaProtobuffers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_avalonya_api_Player_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eu_avalonya_api_Player_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016avalonya.proto\022\017eu.avalonya.api\"g\n\006Pla" +
      "yer\022\014\n\004uuid\030\001 \001(\014\022\014\n\004name\030\002 \001(\t\022\016\n\006rankI" +
      "d\030\003 \001(\005\022\022\n\nfirstLogin\030\004 \001(\003\022\016\n\006lastIp\030\005 " +
      "\001(\t\022\r\n\005money\030\006 \001(\001B2\n\030eu.avalonya.api.pr" +
      "otobufB\024AvalonyaProtobuffersP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_eu_avalonya_api_Player_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eu_avalonya_api_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eu_avalonya_api_Player_descriptor,
        new java.lang.String[] { "Uuid", "Name", "RankId", "FirstLogin", "LastIp", "Money", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
