// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avalonya.proto

package eu.avalonya.api.protobuf;

/**
 * Protobuf type {@code eu.avalonya.api.Player}
 */
public final class Player extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:eu.avalonya.api.Player)
    PlayerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Player.newBuilder() to construct.
  private Player(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Player() {
    uuid_ = com.google.protobuf.ByteString.EMPTY;
    name_ = "";
    lastIp_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Player();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.avalonya.api.protobuf.AvalonyaProtobuffers.internal_static_eu_avalonya_api_Player_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.avalonya.api.protobuf.AvalonyaProtobuffers.internal_static_eu_avalonya_api_Player_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.avalonya.api.protobuf.Player.class, eu.avalonya.api.protobuf.Player.Builder.class);
  }

  public static final int UUID_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString uuid_;
  /**
   * <code>bytes uuid = 1;</code>
   * @return The uuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getUuid() {
    return uuid_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RANKID_FIELD_NUMBER = 3;
  private int rankId_;
  /**
   * <code>int32 rankId = 3;</code>
   * @return The rankId.
   */
  @java.lang.Override
  public int getRankId() {
    return rankId_;
  }

  public static final int FIRSTLOGIN_FIELD_NUMBER = 4;
  private long firstLogin_;
  /**
   * <code>int64 firstLogin = 4;</code>
   * @return The firstLogin.
   */
  @java.lang.Override
  public long getFirstLogin() {
    return firstLogin_;
  }

  public static final int LASTIP_FIELD_NUMBER = 5;
  private volatile java.lang.Object lastIp_;
  /**
   * <code>string lastIp = 5;</code>
   * @return The lastIp.
   */
  @java.lang.Override
  public java.lang.String getLastIp() {
    java.lang.Object ref = lastIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastIp_ = s;
      return s;
    }
  }
  /**
   * <code>string lastIp = 5;</code>
   * @return The bytes for lastIp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastIpBytes() {
    java.lang.Object ref = lastIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MONEY_FIELD_NUMBER = 6;
  private double money_;
  /**
   * <code>double money = 6;</code>
   * @return The money.
   */
  @java.lang.Override
  public double getMoney() {
    return money_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!uuid_.isEmpty()) {
      output.writeBytes(1, uuid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (rankId_ != 0) {
      output.writeInt32(3, rankId_);
    }
    if (firstLogin_ != 0L) {
      output.writeInt64(4, firstLogin_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastIp_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, lastIp_);
    }
    if (java.lang.Double.doubleToRawLongBits(money_) != 0) {
      output.writeDouble(6, money_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!uuid_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, uuid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (rankId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, rankId_);
    }
    if (firstLogin_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, firstLogin_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastIp_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, lastIp_);
    }
    if (java.lang.Double.doubleToRawLongBits(money_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, money_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.avalonya.api.protobuf.Player)) {
      return super.equals(obj);
    }
    eu.avalonya.api.protobuf.Player other = (eu.avalonya.api.protobuf.Player) obj;

    if (!getUuid()
        .equals(other.getUuid())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (getRankId()
        != other.getRankId()) return false;
    if (getFirstLogin()
        != other.getFirstLogin()) return false;
    if (!getLastIp()
        .equals(other.getLastIp())) return false;
    if (java.lang.Double.doubleToLongBits(getMoney())
        != java.lang.Double.doubleToLongBits(
            other.getMoney())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + getUuid().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + RANKID_FIELD_NUMBER;
    hash = (53 * hash) + getRankId();
    hash = (37 * hash) + FIRSTLOGIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFirstLogin());
    hash = (37 * hash) + LASTIP_FIELD_NUMBER;
    hash = (53 * hash) + getLastIp().hashCode();
    hash = (37 * hash) + MONEY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMoney()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.avalonya.api.protobuf.Player parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.avalonya.api.protobuf.Player parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.avalonya.api.protobuf.Player parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.avalonya.api.protobuf.Player parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.avalonya.api.protobuf.Player parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.avalonya.api.protobuf.Player parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.avalonya.api.protobuf.Player parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.avalonya.api.protobuf.Player parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.avalonya.api.protobuf.Player parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.avalonya.api.protobuf.Player parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.avalonya.api.protobuf.Player parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.avalonya.api.protobuf.Player parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.avalonya.api.protobuf.Player prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code eu.avalonya.api.Player}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:eu.avalonya.api.Player)
      eu.avalonya.api.protobuf.PlayerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.avalonya.api.protobuf.AvalonyaProtobuffers.internal_static_eu_avalonya_api_Player_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.avalonya.api.protobuf.AvalonyaProtobuffers.internal_static_eu_avalonya_api_Player_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.avalonya.api.protobuf.Player.class, eu.avalonya.api.protobuf.Player.Builder.class);
    }

    // Construct using eu.avalonya.api.protobuf.Player.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uuid_ = com.google.protobuf.ByteString.EMPTY;

      name_ = "";

      rankId_ = 0;

      firstLogin_ = 0L;

      lastIp_ = "";

      money_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.avalonya.api.protobuf.AvalonyaProtobuffers.internal_static_eu_avalonya_api_Player_descriptor;
    }

    @java.lang.Override
    public eu.avalonya.api.protobuf.Player getDefaultInstanceForType() {
      return eu.avalonya.api.protobuf.Player.getDefaultInstance();
    }

    @java.lang.Override
    public eu.avalonya.api.protobuf.Player build() {
      eu.avalonya.api.protobuf.Player result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.avalonya.api.protobuf.Player buildPartial() {
      eu.avalonya.api.protobuf.Player result = new eu.avalonya.api.protobuf.Player(this);
      result.uuid_ = uuid_;
      result.name_ = name_;
      result.rankId_ = rankId_;
      result.firstLogin_ = firstLogin_;
      result.lastIp_ = lastIp_;
      result.money_ = money_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.avalonya.api.protobuf.Player) {
        return mergeFrom((eu.avalonya.api.protobuf.Player)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.avalonya.api.protobuf.Player other) {
      if (other == eu.avalonya.api.protobuf.Player.getDefaultInstance()) return this;
      if (other.getUuid() != com.google.protobuf.ByteString.EMPTY) {
        setUuid(other.getUuid());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getRankId() != 0) {
        setRankId(other.getRankId());
      }
      if (other.getFirstLogin() != 0L) {
        setFirstLogin(other.getFirstLogin());
      }
      if (!other.getLastIp().isEmpty()) {
        lastIp_ = other.lastIp_;
        onChanged();
      }
      if (other.getMoney() != 0D) {
        setMoney(other.getMoney());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              uuid_ = input.readBytes();

              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 24: {
              rankId_ = input.readInt32();

              break;
            } // case 24
            case 32: {
              firstLogin_ = input.readInt64();

              break;
            } // case 32
            case 42: {
              lastIp_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 49: {
              money_ = input.readDouble();

              break;
            } // case 49
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private com.google.protobuf.ByteString uuid_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes uuid = 1;</code>
     * @return The uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getUuid() {
      return uuid_;
    }
    /**
     * <code>bytes uuid = 1;</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes uuid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      
      uuid_ = getDefaultInstance().getUuid();
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int rankId_ ;
    /**
     * <code>int32 rankId = 3;</code>
     * @return The rankId.
     */
    @java.lang.Override
    public int getRankId() {
      return rankId_;
    }
    /**
     * <code>int32 rankId = 3;</code>
     * @param value The rankId to set.
     * @return This builder for chaining.
     */
    public Builder setRankId(int value) {
      
      rankId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rankId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRankId() {
      
      rankId_ = 0;
      onChanged();
      return this;
    }

    private long firstLogin_ ;
    /**
     * <code>int64 firstLogin = 4;</code>
     * @return The firstLogin.
     */
    @java.lang.Override
    public long getFirstLogin() {
      return firstLogin_;
    }
    /**
     * <code>int64 firstLogin = 4;</code>
     * @param value The firstLogin to set.
     * @return This builder for chaining.
     */
    public Builder setFirstLogin(long value) {
      
      firstLogin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 firstLogin = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstLogin() {
      
      firstLogin_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object lastIp_ = "";
    /**
     * <code>string lastIp = 5;</code>
     * @return The lastIp.
     */
    public java.lang.String getLastIp() {
      java.lang.Object ref = lastIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lastIp = 5;</code>
     * @return The bytes for lastIp.
     */
    public com.google.protobuf.ByteString
        getLastIpBytes() {
      java.lang.Object ref = lastIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lastIp = 5;</code>
     * @param value The lastIp to set.
     * @return This builder for chaining.
     */
    public Builder setLastIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastIp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lastIp = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastIp() {
      
      lastIp_ = getDefaultInstance().getLastIp();
      onChanged();
      return this;
    }
    /**
     * <code>string lastIp = 5;</code>
     * @param value The bytes for lastIp to set.
     * @return This builder for chaining.
     */
    public Builder setLastIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastIp_ = value;
      onChanged();
      return this;
    }

    private double money_ ;
    /**
     * <code>double money = 6;</code>
     * @return The money.
     */
    @java.lang.Override
    public double getMoney() {
      return money_;
    }
    /**
     * <code>double money = 6;</code>
     * @param value The money to set.
     * @return This builder for chaining.
     */
    public Builder setMoney(double value) {
      
      money_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double money = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMoney() {
      
      money_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:eu.avalonya.api.Player)
  }

  // @@protoc_insertion_point(class_scope:eu.avalonya.api.Player)
  private static final eu.avalonya.api.protobuf.Player DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.avalonya.api.protobuf.Player();
  }

  public static eu.avalonya.api.protobuf.Player getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Player>
      PARSER = new com.google.protobuf.AbstractParser<Player>() {
    @java.lang.Override
    public Player parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Player> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Player> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.avalonya.api.protobuf.Player getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

