// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avalonya.proto

package eu.avalonya.api.protobuf;

public interface PlayerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eu.avalonya.api.Player)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes uuid = 1;</code>
   * @return The uuid.
   */
  com.google.protobuf.ByteString getUuid();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 rankId = 3;</code>
   * @return The rankId.
   */
  int getRankId();

  /**
   * <code>int64 firstLogin = 4;</code>
   * @return The firstLogin.
   */
  long getFirstLogin();

  /**
   * <code>string lastIp = 5;</code>
   * @return The lastIp.
   */
  java.lang.String getLastIp();
  /**
   * <code>string lastIp = 5;</code>
   * @return The bytes for lastIp.
   */
  com.google.protobuf.ByteString
      getLastIpBytes();

  /**
   * <code>double money = 6;</code>
   * @return The money.
   */
  double getMoney();
}
